### ISSUE TITLE
I followed the steps but there were no flashcards created...

### ISSUE THREAD

**Issue by dmetry** [ryanjamurphy/Create-flashcards-in-Anki-from-PDFs-using-Skim-and-DEVONthink-#1]
I'm using a document that has headlines and bullet points below the headlines. I've highlighted the headlines.

**Comment by ryanjamurphy** [comment]
Oof, it’s been a while since I’ve used or maintained this script, so I may be of limited support. 

If you’re highlighting a PDF’s headings, the resulting flashcards will be just blank lines, I believe. This works best if you highlight a phrase in a paragraph, as the script creates flashcards of the paragraph with the highlighted part removed.

What happens when you run the script?

**Comment by dmetry** [comment]
It doesn’t create any flash cards

**Comment by dmetry** [comment]
I guess it only works when a single word or phrase is highlighted within a paragraph... would you be able to tell me how I could modify the code so that it would create cards with headline and bullet points?

**Comment by dmetry** [comment]
Resolved
